### ISSUE TITLE
dead (404)

### ISSUE THREAD

**Issue by marcelloh** [Riu/phalconization#10]
The following seem dead (give 404)
https://github.com/oleksandr-torosh/phalcon-modular-app
https://github.com/blackbunny/Url-Shortener- seems dead
https://github.com/nexik/phalcon-form-decorators
https://github.com/hikaliv/PhalconWeb

**Comment by sergeyklay** [comment]
Check https://github.com/sergeyklay/awesome-phalcon :)

**Comment by marcelloh** [comment]
I am looking for webtest, but somehow all the projects I encountered in your list, don't use it.
:-(
But now you gave me hope, and a lot of exploring to do. Thanks! :-)
